Products =[
	{
	"id": 1,
	"name":"Hydra Glow Moisturizer",
	"category":["dry","normal"],
	"skin_type":["oily", "combination"],
	"concerns":["dryness", "dullness"],
	"price": 2000, "BDT",
	"ingredients":["hyaluronic acid","vitamin C"],
         },
	{
	"id": 2,
	"name":"Alovera Facewash By RevSkin BD",
	"category":"Cleanser",
	 "skin_types": ["oily", "combination"],
	"concerns":["oily", "combination"],
	"price": 1500, "BDT",
	"ingredients":["hyaluronic acid","vitamin C"],
	},
	{
	"id": 3,
	"name":"Apsara Barrier Repair Serum",
	"category":"Serum",
	"skin_types": ["sensitive"],
	"concerns":["oily", "combination"],
	"price": 1500, "BDT",
	"ingredients":["hyaluronic acid","vitamin C"],
	},
	{
        "id": 4,
        "name": "Glamour Sunscreen SPF 30",
        "category": "Sunscreen",
        "skin_types": ["combination", "oily", "normal"],
        "concerns": ["sun-protection", "oil-control"],
        "price": 2175.00, "BDT",
        "ingredients": ["zinc oxide", "niacinamide"],
    },
	{
        "id":5,
        "name": "Nourish Night Oil",
        "category": "Treatment",
        "skin_types": ["dry", "normal"],
        "concerns": ["anti-aging", "dryness"],
        "price":3015.00, "BDT",
        "ingredients": "vitamin E",
    },
]