PRODUCTS = [
    {
        "id": 1,
        "name": "HydraGlow Moisturizer",
        "category": "Moisturizer",
        "skin_types": ["dry", "normal"],
        "concerns": ["dryness", "dullness"],
        "price": 2750.00,
        "ingredients": ["hyaluronic acid", "vitamin C"],
    },
    {
        "id": 2,
        "name": "Clarify Cleanser",
        "category": "Cleanser",
        "skin_types": ["oily", "combination"],
        "concerns": ["acne", "oil-control"],
        "price": 1600.00,
        "ingredients": ["salicylic acid", "tea tree oil"],
    },
    {
        "id": 3,
        "name": "Calm Barrier Serum",
        "category": "Serum",
        "skin_types": ["sensitive"],
        "concerns": ["redness", "barrier repair"],
        "price": 3520.00,
        "ingredients": ["ceramides", "panthenol"],
    },
    {
        "id": 4,
        "name": "Balance SPF 30",
        "category": "Sunscreen",
        "skin_types": ["combination", "oily", "normal"],
        "concerns": ["sun-protection", "oil-control"],
        "price": 2175.00,
        "ingredients": ["zinc oxide", "niacinamide"],
    },
    {
        "id": 5,
        "name": "Nourish Night Oil",
        "category": "Treatment",
        "skin_types": ["dry", "normal"],
        "concerns": ["anti-aging", "dryness"],
        "price": 3015.00,
        "ingredients": ["squalane", "vitamin E"],
    },
]
